### ISSUE TITLE
New keywords

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-tmbundle#1]
I guess we need to add keywords such as `ulevel`, `hlevel` and `variable`

**Comment by imkiva** [comment]
keywords added: `bind`, `looser`, `tighter`, `ulevel`, `hlevel`, `uSet`
statement added: `'variable' ids type`

**Comment by ice1000** [comment]
Please remove `uSet`

**Comment by ice1000** [comment]
I've removed it in my dev branch, because I decided to change the way desugaring works and `uSet` becomes useless

**Comment by imkiva** [comment]
Removed in 9cbf91a7569272b8f27ec483f20c9381c639b5fe
